name = "TBA"
author = "Slash"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75532449886a3a9b36ebb655f4d50a752b91c7e798d187dff9c644fdbe9ac1bb"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
