name = "TBA"
author = "Slash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8731cba83854ee692d86c40d38b8a6eb1d374e85a10dc533a473fd0966537532"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
